---
title: "gtsummary in quarto"
format:
  html:
    theme: yeti
execute:
  echo: false
  error: true
---

```{r}
#| include: false
library(tidyverse)
library(gtsummary)
nlsy_cols <- c("glasses", "eyesight", "sleep_wkdy", "sleep_wknd", 
               "id", "nsibs", "samp", "race_eth", "sex", "region", 
               "income", "res_1980", "res_2002", "age_bir")
nlsy <- read_csv(here::here("data", "raw", "nlsy.csv"), 
                 na = c("-1", "-2", "-3", "-4", "-5", "-998"),
                 skip = 1, col_names = nlsy_cols) |> 
  mutate(region_cat = factor(region, labels = c("Northeast", "North Central", "South", "West")),
         sex_cat = factor(sex, labels = c("Male", "Female")),
         race_eth_cat = factor(race_eth, labels = c("Hispanic", "Black", "Non-Black, Non-Hispanic")),
         eyesight_cat = factor(eyesight, labels = c("Excellent", "Very good", "Good", "Fair", "Poor")),
         glasses_cat = factor(glasses, labels = c("No", "Yes"))) 
```

# Customization of `tbl_summary()`

```{r}
#| label: tbl-descr
#| tbl-cap: "Charatristics of study particpants"
table1 <- tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir)) |> 
  add_overall(last = TRUE)
table1


```


```{r}
nrow(nlsy)
```


```{r}
mean_sleep_wknd <- mean(nlsy$sleep_wknd, na.rm = TRUE)
mean_sleep_wknd
```

The mean number of hours of sleep on weekends was`r mean(nlsy$sleep_wknd, na.rm = TRUE)`.
